{
  pages(where: {title: "Egresados"}) {
    edges {
      node {
        template {
          ... on DefaultTemplate {
            heroPaginas {
              textoBotonRojo
              titulo
              imagenDeFondo {
                altText
                srcSet
                sourceUrl
              }
            }
          }
        }
      }
    }
  }
}
