{ 
 pages(where: {title: "Programas"}) {
    edges {
      node {
        template {
          ... on DefaultTemplate {
            heroPaginas {
              textoBotonRojo
              titulo
              imagenDeFondo {
                altText
                srcSet
                sourceUrl
              }
            }
          }
        }
      }
    }
  }
  
 cPTCursosATC(where: {status: PUBLISH}) {
    nodes {
      id
      cPTCursoATCId
      title
      featuredImage {
        node {
          altText
          srcSet
          sourceUrl
        }
      }
      configuracionCursosATC {
        categoria
        sede
        certificadoOtorgado
        descripcion
        duracion
        fechaDeInicio
        jornada
        modalidad
        pdfDelPrograma {
          sourceUrl
        }
        miniatura {
          altText
          srcSet
          sourceUrl
        }
      }
    }
  }

}
