{
  plantillas(where: {title: "slider"}) {
    nodes {
      cmbSlider {
        slide {
          informacionDelSlide {
            titulo
            textoEnFranjaRoja
            subtitulo
            posicionDelTexto
            imagen {
              altText
              title
              srcSet
              sourceUrl
            }
          }
        }
      }
    }
  }
}
