{
  pages(where: { title: "Programas" }) {
    edges {
      node {
        template {
          ... on DefaultTemplate {
            heroPaginas {
              textoBotonRojo
              titulo
              imagenDeFondo {
                altText
                srcSet
                sourceUrl
              }
            }
          }
        }
      }
    }
  }

  cPTCursosATC(where: { status: PUBLISH }) {
    nodes {
      id
      cPTCursoATCId
      title
      featuredImage {
        node {
          altText
          srcSet
          sourceUrl
        }
      }
      configuracionCursosATC {
        categoria
        sede
        certificadoOtorgado
        descripcion
        duracion
        fechaDeInicio
        jornada
        modalidad
        pdfDelPrograma {
          sourceUrl
        }
        miniatura {
          altText
          srcSet
          sourceUrl
        }
      }
    }
  }
}

# query MyQuery {
#   cursos(where: { status: PUBLISH }) {
#     edges {
#       node {
#         cursos_mb {
#           categoria
#           certificacion
#           descripcion
#           duracion
#           excerpt
#           fechaDeInicio
#           jornada
#           modalidad
#           precio
#           sede
#           miniatura {
#             altText
#             sourceUrl
#             srcSet
#           }
#           pdfPlanEstudios {
#             sourceUrl
#           }
#         }
#         title
#         id
#         featuredImage {
#           node {
#             altText
#             sourceUrl
#             srcSet
#           }
#         }
#       }
#     }
#   }
# }

# query MyQuery {
#   cPTCursosATC(where: { status: PUBLISH }) {
#     nodes {
#       title
#       id
#       featuredImage {
#         node {
#           altText
#           caption
#           id
#           srcSet
#           sourceUrl
#         }
#       }
#       configuracionCursosATC {
#         fechaDeInicio
#         valor
#         modalidad
#         sede
#         duracion
#         categoria
#         certificadoOtorgado
#         jornada
#         descripcion
#         miniatura {
#           altText
#           id
#           srcSet
#           sourceUrl
#         }
#         pdfDelPrograma {
#           uri
#         }
#       }
#     }
#   }
# }
