query($id: ID!) {
  egresadoBy(id: $id) {
    id
    title
    featuredImage {
      node {
        altText
        srcSet
        sourceUrl
        id
      }
    }
    cmbEgresados {
      titulo
      sitioWeb
      correo
      descripcion
      redesSociales {
        nombreDeUsuario
        redSocial
        urlDeLaRedSocial
      }
      miniatura {
        altText
        srcSet
        sourceUrl
        id
      }
    }
  }
}
